"""Example report skeleton — copy this pattern for a real report, then delete
this file once a real 01_....py report exists.

A report reads one or more experiments' output from experiment_results/,
states the thesis(es) they support, and writes a self-contained HTML (or
Markdown) writeup to report_results/<this_script_name>/ — regenerated by
re-running this script, never hand-edited after the fact.

Run:
    PYTHONPATH="$PWD" python reports/01_example_report.py
"""

from reports.common import result_dir

OUT_DIR = result_dir("01_example_report")


def main():
    # 1. Read whatever experiment_results/NN_.../*.csv|json this report
    #    synthesizes.
    # 2. State the thesis in plain language, backed by specific numbers.
    # 3. Render to a single self-contained HTML file (inline CSS, no external
    #    asset dependencies) so it's readable standalone.
    report_html = """<!doctype html>
<html><head><meta charset="utf-8"><title>Example report</title></head>
<body>
<h1>Example report</h1>
<p>Replace this with a real synthesis of one or more experiments' findings.</p>
</body></html>
"""
    (OUT_DIR / "report.html").write_text(report_html)
    print(f"wrote {OUT_DIR / 'report.html'}")


if __name__ == "__main__":
    main()
