"""Example report skeleton -- copy this pattern for a real report, then delete
this file (and reports/01_example/) once a real 01_....py report exists.

Thin orchestrator only: calls collect (if present) -> compute -> render, and
writes the result to report_results/<this_script_name>/. Regenerated by
re-running this script, never hand-edited after the fact. Stats computation
lives in 01_example/compute.py, HTML/wording lives in 01_example/render.py --
see research_rules/06-report-separation.md for why they're kept apart.

Run:
    PYTHONPATH="$PWD" python reports/01_example_report.py
"""

import importlib

from reports.common import result_dir

# Package name starts with a digit (matches the NN_name numbering
# convention), so it can't be a plain dotted import -- see rule 06.
compute = importlib.import_module("reports.01_example.compute")
render = importlib.import_module("reports.01_example.render")

OUT_DIR = result_dir("01_example_report")


def main():
    stats = compute.compute_stats()
    report_html = render.render_html(stats)
    (OUT_DIR / "report.html").write_text(report_html)
    print(f"wrote {OUT_DIR / 'report.html'}")


if __name__ == "__main__":
    main()
